import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../globals.css";


const fontLato = Lato({ subsets: ['latin-ext'], weight: '400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string}
}>) {
  return (
    <html lang={locale}>
      <body className={fontLato.className}>{children}</body>
    </html>
  );
}
